### ISSUE TITLE
osm2pgsql crash

### ISSUE THREAD

**Issue by alexvaler** [openstreetmap/osm2pgsql#2370]
## What version of osm2pgsql are you using?
osm2pgsql version 2.1.1  

## What operating system and PostgreSQL/PostGIS version are you using?
Windows 10
Database version: 17.5                                                                                                                                                                        PostGIS version: 3.5               

## Tell us something about your system
Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz   3.41 GHz
16,0 ГБ SSD

## What did you do exactly?

C:\Distr\Postgres\osm2pgsql-bin>osm2pgsql.exe -c -s -d gis --user postgres --port 5439 f31cc82f-32e8-4fe8-a535-eb8da64efc55.osm.pbf
2025-07-31 10:04:15  osm2pgsql version 2.1.1
2025-07-31 10:04:15  Database version: 17.5
2025-07-31 10:04:15  PostGIS version: 3.5 

C:\Distr\Postgres\osm2pgsql-bin>           

## What did you expect to happen?

Load file to database. 

## What did happen instead?

Имя сбойного приложения: osm2pgsql.exe, версия: 0.0.0.0, метка времени: 0x67fcc054
Имя сбойного модуля: MSVCP140.dll, версия: 14.32.31326.0, метка времени: 0x7255e0ca
Код исключения: 0xc0000005
Смещение ошибки: 0x0000000000013278
Идентификатор сбойного процесса: 0x4d68
Время запуска сбойного приложения: 0x01dc01e978ed3330
Путь сбойного приложения: C:\Distr\Postgres\osm2pgsql-bin\osm2pgsql.exe
Путь сбойного модуля: C:\Windows\SYSTEM32\MSVCP140.dll
Идентификатор отчета: 51ab3739-6665-443a-b84b-efc2bf8845e7
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 

## What did you do to try analyzing the problem?

Test on different files (70 mb - 3gb). Always same crash.

**Comment by lonvia** [comment]
Can you please provide a minimal example pbf (preferably not larger than 1 or 2 MB) that produces the crash.

**Comment by lonvia** [comment]
The file works fine on Linux, so this is a Windows issue for which we can only give limited support, I'm afraid.

Can you please try with the latest build from https://github.com/osm2pgsql-dev/osm2pgsql/actions/runs/16625471270 ? This might be the same issue as #2326, which was fixed in latest master.

If it still crashes, then we'd need a full backtrace of the crash.

**Comment by alexvaler** [comment]
Still crashes with latest build. Can you give me simple way to obtain backtrace?

**Comment by lonvia** [comment]
If somebody on Windows can help the OP with creating a stacktrace that would be nice. Otherwise there isn't much I can do.

**Comment by mboeringa** [comment]
> If somebody on Windows can help the OP with creating a stacktrace that would be nice. Otherwise there isn't much I can do.

I doubt this is an osm2pgsql issue. 

I think the OP needs to re-install or update his Microsoft Visual C++ Redistributable, as the failing **'MSVCP140.dll'** seems to be part of that:
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

I have all the below versions installed, including the latest 2015-2022 version. Having more than one version installed is apparently no problem, as I was never prompted to uninstall older versions, but a newer version may be needed for osm2pgsql.

<img width="690" height="880" alt="Image" src="https://github.com/user-attachments/assets/951568f0-9200-4725-b812-a94901c63333" />

**Comment by mboeringa** [comment]
Alternatively, for a stack trace, Microsoft's **WinDbg** might be an option:
https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/
